# Use Node.js 20 as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr/src/app/front-end


# Copy necessary files into the container
COPY . .

# Other instructions...


# Copy package.json and package-lock.json (or yarn.lock) to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire application code
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Define the command to start the application
CMD ["npm", "start"]
