POST http://localhost:5000/users
Content-Type: application/json

{
	"name": "test",
	"email": "Test3@ucf.edu",
	"password": "hello124"
}

###

POST http://localhost:5000/expenses
Content-Type: application/json

{
	"type": "Test30",
	"quanity": 10,
	"price": 10,
	"user_id": "6553d40d829184f074e19de9"

}

###

GET http://localhost:5000/user
Content-type: application/json

{
	"_id": "6553d40d829184f074e19de9"
}

###

POST http://localhost:5000/users/add_expense
Content-Type: application/json

{
	"user_id": "6553d40d829184f074e19de9",
	"exp_id": "testid"
}

###

POST http://localhost:5000/expense
Content-Type: application/json

{
	"_id": "6553d40d829184f074e19de9"
}