POST http://localhost:5000/users
Content-Type: application/json

{
	"email": "Test2@ucf.edu",
	"password": "hello124"
}

###

POST http://localhost:5000/expenses
Content-Type: application/json

{
	"type": "Test",
	"quanity": 10,
	"price": 10

}

###

GET http://localhost:5000/users
